name: amix
description: a package for creating Servers.
version: 0.0.14
homepage: https://github.com/peter-parker-a/amix/

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
